Vagrant.configure('2') do |config|
  config.vm.box = 'box-cutter/fedora20'

  config.vm.network 'forwarded_port', guest: 80, host: 8080
  config.vm.synced_folder '.', '/var/www'

  config.vm.provision 'shell', path: 'setup.sh', privileged: false
  config.vm.provision 'file', source: 'nginx.conf', destination: '/etc/nginx/nginx.conf'
end
